extends RefCounted
## Terrain map generated by tools/build_map.py. One cell = one world unit.

const DEEP := 0
const SHALLOW := 1
const GRASS := 2
const SAND := 3
const SNOW := 4
const MOUNTAIN := 5
const RIVER := 6
const LAKE := 7
const VOID := 8

var width: int = 0
var height: int = 0
var terrain: PackedByteArray
var coast: PackedByteArray          # 1 = playable land touching the sea
var land_total: int = 0
var land_cells: PackedInt32Array    # indices of all playable land cells
var coast_cells: PackedInt32Array   # indices of playable land cells touching the sea
var terrain_texture: ImageTexture


func _init(dir: String = "res://assets/map/") -> void:
	var f := FileAccess.open(dir + "map.json", FileAccess.READ)
	assert(f != null, "map.json missing - run python3 tools/build_map.py")
	var meta = JSON.parse_string(f.get_as_text())
	width = int(meta["width"])
	height = int(meta["height"])
	land_total = int(meta["land_total"])
	terrain = FileAccess.get_file_as_bytes(dir + "terrain.dat")
	coast = FileAccess.get_file_as_bytes(dir + "coast.dat")
	assert(terrain.size() == width * height and coast.size() == width * height, "map data size mismatch")
	terrain_texture = ImageTexture.create_from_image(Image.create_from_data(width, height, false, Image.FORMAT_R8, terrain))
	var cells := PackedInt32Array()
	var coasts := PackedInt32Array()
	for i in width * height:
		var t := terrain[i]
		if t >= GRASS and t <= RIVER:
			cells.append(i)
			if coast[i] == 1:
				coasts.append(i)
	land_cells = cells
	coast_cells = coasts


func size() -> int:
	return width * height


func is_land(i: int) -> bool:
	var t := terrain[i]
	return t >= GRASS and t <= RIVER


func is_sea(i: int) -> bool:
	return terrain[i] <= SHALLOW


func is_coast(i: int) -> bool:
	return coast[i] == 1


@warning_ignore("integer_division")
func cell(i: int) -> Vector2i:
	return Vector2i(i % width, i / width)


func index(c: Vector2i) -> int:
	return c.y * width + c.x


func in_bounds(c: Vector2i) -> bool:
	return c.x >= 0 and c.y >= 0 and c.x < width and c.y < height


func neighbors(i: int) -> PackedInt32Array:
	var out := PackedInt32Array()
	var x := i % width
	if x > 0:
		out.append(i - 1)
	if x < width - 1:
		out.append(i + 1)
	if i >= width:
		out.append(i - width)
	if i + width < width * height:
		out.append(i + width)
	return out
